### ISSUE TITLE
Issue with some db in DOWNLOAD state

### ISSUE THREAD

**Issue by arsalan-akhtar** [Matgenix/jobflow-remote#161]
Hello everyone,
I am encountering an issue with a MongoDB update query in DOWNLOAD state. however if i use another db like atlas everything is fine! ... 
testing the projcet check --errors are also fine (the jobstore and the queue store dbs are working)
im using : 
pymongo                       4.8.0

 here is the error:

```
The selected project is uclmodl from config file /home/akhtar/.jfremote/uclmodl.yaml
                                                                Jobs info                                                                
┏━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┓
┃ DB id ┃ Name                             ┃ State      ┃ Job id  (Index)                           ┃ Worker       ┃ Last updated [CET] ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━┩
│ 1     │ Relaxation calculation-ions-only │ DOWNLOADED │ 2e777f63-ca87-47ad-8604-02ceaaea1e05  (1) │ local_worker │ 2024-08-06 17:01   │
└───────┴──────────────────────────────────┴────────────┴───────────────────────────────────────────┴──────────────┴────────────────────┘
Some jobs (state in orange) have failed while interacting with the worker, but will be retried.
Get more information about the errors with 'jf job info JOB_ID'
(abinit) akhtar@PC-SE22-357:~$ jf -p uclmodl job info 1
/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
The selected project is uclmodl from config file /home/akhtar/.jfremote/uclmodl.yaml
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ created_on = '2024-08-06 16:54'                                                                                                                                    │
│      db_id = '1'                                                                                                                                                   │
│      index = 1                                                                                                                                                     │
│   metadata = {'label': 'final-test-arsalan'}                                                                                                                       │
│       name = 'Relaxation calculation-ions-only'                                                                                                                    │
│    parents = []                                                                                                                                                    │
│   priority = 0                                                                                                                                                     │
│     remote = {                                                                                                                                                     │
│                  'step_attempts': 3,                                                                                                                               │
│                  'process_id': '205663',                                                                                                                           │
│                  'retry_time_limit': '2024-08-06 17:21',                                                                                                           │
│                  'error': Traceback (most recent call last):                                                                                                       │
│                File "/home/akhtar/2-Areas/Miniconda3-apps-abinit/jobflow-remote/src/jobflow_remote/jobs/jobcontroller.py", line 3316, in lock_job_for_update       │
│                  yield lock                                                                                                                                        │
│                File "/home/akhtar/2-Areas/Miniconda3-apps-abinit/jobflow-remote/src/jobflow_remote/jobs/runner.py", line 538, in advance_state                     │
│                  states_methods[state](lock)                                                                                                                       │
│                File "/home/akhtar/2-Areas/Miniconda3-apps-abinit/jobflow-remote/src/jobflow_remote/jobs/runner.py", line 796, in complete_job                      │
│                  completed = self.job_controller.complete_job(doc, local_path, store)                                                                              │
│                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                              │
│                File "/home/akhtar/2-Areas/Miniconda3-apps-abinit/jobflow-remote/src/jobflow_remote/jobs/jobcontroller.py", line 2838, in complete_job              │
│                  with self.lock_flow(                                                                                                                              │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/contextlib.py", line 137, in __enter__                                             │
│                  return next(self.gen)                                                                                                                             │
│                         ^^^^^^^^^^^^^^                                                                                                                             │
│                File "/home/akhtar/2-Areas/Miniconda3-apps-abinit/jobflow-remote/src/jobflow_remote/jobs/jobcontroller.py", line 3264, in lock_flow                 │
│                  with MongoLock(collection=self.flows, **lock_kwargs) as lock:                                                                                     │
│                File "/home/akhtar/2-Areas/Miniconda3-apps-abinit/jobflow-remote/src/jobflow_remote/utils/db.py", line 265, in __enter__                            │
│                  self.acquire()                                                                                                                                    │
│                File "/home/akhtar/2-Areas/Miniconda3-apps-abinit/jobflow-remote/src/jobflow_remote/utils/db.py", line 210, in acquire                              │
│                  result = self.collection.find_one_and_update(                                                                                                     │
│                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                     │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/collection.py", line 3449, in find_one_and_update            │
│                  return self.__find_and_modify(                                                                                                                    │
│                         ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                    │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/collection.py", line 3110, in __find_and_modify              │
│                  return self.__database.client._retryable_write(                                                                                                   │
│                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                   │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1575, in _retryable_write             │
│                  return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)                                                                │
│                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1461, in _retry_with_session          │
│                  return self._retry_internal(                                                                                                                      │
│                         ^^^^^^^^^^^^^^^^^^^^^                                                                                                                      │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper                         │
│                  return func(self, *args, **kwargs)                                                                                                                │
│                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1507, in _retry_internal              │
│                  ).run()                                                                                                                                           │
│                    ^^^^^                                                                                                                                           │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2353, in run                          │
│                  return self._read() if self._is_read else self._write()                                                                                           │
│                                                            ^^^^^^^^^^^^^                                                                                           │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2470, in _write                       │
│                  return self._func(self._session, conn, self._retryable)  # type: ignore                                                                           │
│                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                           │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/collection.py", line 3096, in _find_and_modify               │
│                  out = self._command(                                                                                                                              │
│                        ^^^^^^^^^^^^^^                                                                                                                              │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/collection.py", line 301, in _command                        │
│                  return conn.command(                                                                                                                              │
│                         ^^^^^^^^^^^^^                                                                                                                              │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/helpers.py", line 342, in inner                              │
│                  return func(*args, **kwargs)                                                                                                                      │
│                         ^^^^^^^^^^^^^^^^^^^^^                                                                                                                      │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/pool.py", line 989, in command                               │
│                  return command(                                                                                                                                   │
│                         ^^^^^^^^                                                                                                                                   │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/network.py", line 212, in command                            │
│                  helpers._check_command_response(                                                                                                                  │
│                File "/home/akhtar/2-Areas/Miniconda3/envs/abinit/lib/python3.12/site-packages/pymongo/helpers.py", line 248, in _check_command_response            │
│                  raise OperationFailure(errmsg, code, response, max_wire_version)                                                                                  │
│              pymongo.errors.OperationFailure: The dollar ($) prefixed field '$set' in '0.$set' is not valid for storage., full error: {'ok': 0.0, 'errmsg': "The   │
│              dollar ($) prefixed field '$set' in '0.$set' is not valid for storage.", 'code': 52, 'codeName': 'DollarPrefixedFieldName'}                           │
│                                                                                                                                                                    │
│              }                                                                                                                                                     │
│    run_dir = '/home/akhtar/1-Projects/UCL-Abiml-Project-atomate2/scratch/scratch-job-remote-uclmodl/2e/77/7f/2e777f63-ca87-47ad-8604-02ceaaea1e05_1'               │
│ start_time = '2024-08-06 16:55'                                                                                                                                    │
│      state = 'DOWNLOADED'                                                                                                                                          │
│ updated_on = '2024-08-06 17:01'                                                                                                                                    │
│       uuid = '2e777f63-ca87-47ad-8604-02ceaaea1e05'                                                                                                                │
│     worker = 'local_worker'
```

**Comment by gpetretto** [comment]
Hi @arsalan-akhtar, 
given the error I suppose it might be related to a functionality not supported by your version of mongodb. Which version of the DB are you running?

**Comment by arsalan-akhtar** [comment]
hey @gpetretto i'm using:
MongoDB server version: 4.0.20

**Comment by gpetretto** [comment]
From what I see [here](https://stackoverflow.com/questions/70617689/mongodb-the-dollar-prefixed-field-is-not-valid-for-storage) indeed it seems that v4.0 does not support a DB operation that is used in the code. Would it be possible for you to upgrade to a more recent version?

I wonder if it may be worth implementing a version that would preserves compatibility with older versions of mongodb (there are likely other operations that will not work with v4.0). However, given that v4.0 reached its EOL [more than 2 years ago](https://www.mongodb.com/legal/support-policy/lifecycles) I am not sure if it would be really worth the effort.

**Comment by arsalan-akhtar** [comment]
I see no problem. I was using Atlas DB and wanted to migrate toward the UCL DB server of the university, but it seems problematic. I'll stick with Atlas then. Thanks.
